query ($link: String!, $nb: Int) {
    categoryElements(link: $link, nb: $nb){
        _id
        title
        h1
        description
        category {name , link}
        tags {name, slug, image {_id}}
        image_large {_id, low, high}
        image_small {_id, low, high}
        link
        created_at
        updated_at
    }
}
