query ($link: String!) {
    categoryElements(link: $link){
        _id
        title
        description
        tags {name, slug}
        image_large {_id, low, high}
        image_small {_id, low, high}
        link
        journal
        authors
        published
        created_at
        updated_at
    }
}
