query($_id: String) {
    post(_id: $_id) {
        _id
        title
        componentName
        description
        published
        journal
        authors
        pdf
        exterlink
        h1
        tagfilter
        content
        tags {_id, name, slug}
        image_large {_id, low, high}
        image_small {_id, low, high}
        category {_id, name, description, title}
        status {_id, name, desc}
        link
        user {_id, name, image}
        created_at
        updated_at
    }
  }