{
    posts{
        _id
        title
        description
        h1
        content
        fiche
        tags {_id, name, slug}
        image_large {_id, low, high}
        image_small {_id, low, high}
        link
        componentName
        user {_id, name, image}
        category {_id, name, description, title}
        status {_id, name, desc}
        created_at
        updated_at
    }
}