
{
    teams{
        _id
        name
        title
        degree
        tags {_id name slug}
        image_large {_id low high}
        link
        content
        email
        twitter
        cv
        google
        linkedin
        researchgate
        github
        created_at
        updated_at
    }
}